apiVersion: v1
kind: Pod
metadata:
  name: livenessprobe
  labels:
    name: livenessprobe
spec:
  containers:
    - name: livenessprobe
      image: Busybox
      command:
        - " 'sh' "
      livenessProbe:
        exec:
          command:
            - "echo"
            - "testing"
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
