apiVersion: v1
kind: Pod
metadata:
  name: testingready
  labels:
    name: testingready
spec:
  containers:
    - name: testingready
      image: nginx
      readinessProbe:
        httpGet:
          path: /
          port: 80

      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: <Port>
