# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  mongoroot_username: dXNlcm5hbWU=
  mongoroot_password: cGFzc3dvcmQ=
